### ISSUE TITLE
Fragmentos Configuración

### ISSUE THREAD

**Issue by zalito12** [Fic-Spinoff/family-care#13]
Crear fragmento configuración VIP.
Crear fragmento configuración Guard.
Añadir botón de configuración y conectar ambos con su actividad.

**Comment by zalito12** [comment]
Terminaré de implementar yo esta parte, meteré algunas opciones de configuración inventadas de momento.

**Comment by zalito12** [comment]
El botón ya está.
Falta crear la actividad de configuración con opciones de relleno para el VIP y otra pata el Guard.

**Comment by zalito12** [comment]
Como comentamos hay que crear una Settings Activity para VIP y otra para el Guard. De momento que guarde los valores en las Shared Prefs aunque no hagamos nada con ellos pero ya ir adelantando.
Algunas opciones que se me ocurren son estas, puedes meterlas en la wiki en un apartado para ir modificando allí y ya queda más a mano:

## VIP
Opciones de configuración para el VIP
### GPS
* Habilitar seguimiento GPS
* Tiempo de refresco (Con opciones a elegir)
* Permitir que los Guards vean mi posición en tiempo real
* Notificarme cuando me salga de una zona de seguridad

### Sensores
* Activar seguimiento pulsómetro
* Activar seguimiento pasos
* Activar seguimiento de actividad

### Cuenta
* Desvincular todas las cuentas
* Cerrar sesión

## Guard
Para el guard por ejemplo
### Notificaciones
* Desactivar notificaciones cuando estoy cerca del VIP
* Desactivar notificaciones cuando otro miembro está cerca del VIP
* Desactivar notificaciones durante la noche (Poder elegir horas)

### GPS
* Recibir notificaciones de zonas de seguridad

### Caídas
* Activar notificaciones de caídas
* Nivel de sensibilidad de caídas (A elegir entre 2 de momento)

### Sensores corporales
* Activar datos de sensores corporales
* Activar alerta de pulso
* Rango pulso normal (Meter dos valores a > b)
* Activar notificación de sedentarismo
* Tiempo máximo sin movimiento (Meter horas y minutos)

### Contacto
* Activar alerta de contacto
* Tiempo máximo sin contactar (Meter un número de días)
* Hora preferida para contactar

### Batería
* Activar notificación de batería
* Nivel de batería crítico

Algunas de estas se deben deshabilitar cuando otro no está activa, por ejemplo no poder configurar el "Nivel de batería" si no está activada la notificación.

**Comment by Diego-Fic** [comment]
La parte de "De momento que guarde los valores en las Shared Prefs aunque no hagamos nada con ellos pero ya ir adelantando" aún no la he terminado, lo termino si puedo en clase. Después tengo que comentarte cambios que he realizado en los layouts. Siento subirte las cosas tan tarde 😓.

**Comment by zalito12** [comment]
Cuando tengas lo que comentamos, de lanzar la actividad para el Guard y para el Vip haz el PR y listo.
