### ISSUE TITLE
Geofencing y GPS

### ISSUE THREAD

**Issue by zalito12** [Fic-Spinoff/family-care#27]
Ampliar el trabajo realizado hasta ahora con el GPS.
Crear una actividad independiente para recoger datos del GPS, mediante una AsyncTask por ejemplo o como indiquen las guías de Android, en el futuro se moverá a un servicio.
Definir una zona en código (sin mapa) y detectar en esta actividad con el GPS cuando se entra sale, etc.

**Comment by zalito12** [comment]
Como vimos el otro día hay que estudiar el uso de las API de Geolocalización y Geofencing de Google y como aplicarlo a nuestra app. Que aprobada esta tarea.

**Comment by zalito12** [comment]
Si no avanzaste mucho en la rama será mejor que la vuelvas a crear desde el master o hagas un rebase cuanto antes porque ha habido varios cambios en el build y demás.

**Comment by bougar** [comment]
Voy a seguir con esta "Issue". Ya he hecho el "merge" de la rama "master".
