### ISSUE TITLE
Mejoras en Mapa y Geofencing

### ISSUE THREAD

**Issue by bougar** [Fic-Spinoff/family-care#41]
* Creación de distintos marcadores para el mapa, en función de su uso ( distintos colores, textos, ... )
* Refactorizar el servicio de Geofence, diviendolo en dos "Intent Services" que solo se ejecuten cuando sea necesario añadir o quitar Geofences.
* Configurar notificaciones
* Comunicar las Geofences entre dispositivos

**Comment by zalito12** [comment]
Como ya te dije, yo me puedo encargar de la parte de las comunicaciones entre dispositivos, es decir en el VIP se detectará que hay que dar aviso  y yo puedo implementar la parte de enviar el aviso a los Guards.
Por el resto ok, la pongo aceptada ya.

**Comment by zalito12** [comment]
¿Vas a subir cambios después de lo que hablamos el otro día?
Cuando esté listo ya lo miro para integrarlo con firebase.
